# Generated by Django 4.0.2 on 2023-05-16 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('client_fname', models.CharField(max_length=50)),
                ('client_lname', models.CharField(max_length=50)),
                ('client_pass', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('service_name', models.CharField(max_length=50)),
                ('service_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('record_start_date', models.DateField()),
                ('record_deadline', models.DateField(blank=True, null=True)),
                ('record_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.client')),
                ('record_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.service')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('employee_fname', models.CharField(max_length=50)),
                ('employee_lname', models.CharField(max_length=50)),
                ('employee_phone', models.CharField(max_length=9)),
                ('employee_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.post')),
            ],
        ),
    ]
