# Generated by Django 4.0.2 on 2023-05-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_salary',
            field=models.FloatField(default=2000.0),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_deadline',
            field=models.DateField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.FloatField(default=20.0),
        ),
    ]
