# Generated by Django 4.0.2 on 2023-05-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_post_post_salary_alter_client_client_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('location_street', models.CharField(max_length=255)),
                ('location_number', models.CharField(max_length=5)),
                ('location_postcode', models.CharField(max_length=6)),
                ('location_phone', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.location'),
        ),
        migrations.AddField(
            model_name='record',
            name='record_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.location'),
        ),
    ]
