# Generated by Django 4.0.2 on 2023-06-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_employee_location_alter_employee_posn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(default='Rzeszów', max_length=255),
        ),
    ]
