# Generated by Django 4.0.2 on 2023-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_location_alter_record_record_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
