# Generated by Django 4.0.2 on 2023-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_rename_post_posn_rename_client_email_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posn',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
