# Generated by Django 4.0.2 on 2023-06-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_client_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(default='Canada', max_length=255),
        ),
    ]
